version: "3.8"

services:
  payment-service:
    image: dinildulneth/payment-service:latest
    container_name: payment-service
    ports:
      - "5010:5010"
    env_file:
      - .env # Uses My .env file from the same folder
    environment:
      # Override any if needed
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5010
