apiVersion: v1
kind: Secret
metadata:
  name: carelink-secrets
  namespace: carelink
type: Opaque
data:
  JWT_KEY: ek4zSzl4WThzN0ZKazJsUXZXbVA0YVIxVDZ1RW9CNWNYc2Z5a21kdSQmREpVU0w5ZEhmRzhKa0wycFE9PQ==
  # RabbitMq__Password: Z3Vlc3Q=
  PayHere__Secret: eW91ci1wYXloZXJlLXNlY3JldA==
  PostgresPassword: YWRtaW4xMjM=
